import { Token } from "../../types";

// export const stellarTokens: Token[] = [
//   {
//     name: "Dogstar",
//     address: "CDPU5TPNUMZ5JY3AUSENSINOEB324WI65AHI7PJBUKR3DJP2ULCBWQCS",
//     graphAddress: "CDPU5TPNUMZ5JY3AUSENSINOEB324WI65AHI7PJBUKR3DJP2ULCBWQCS",
//     symbol: "XTAR",
//     logoURI: "https://www.dogstarcoin.com/assets/img/dogstarcoin-logo.png",
//     decimals: 7,
//     coinGeckoId: "",
//   },
//   {
//     name: "USDCoin",
//     address: "CCGCRYUTDRP52NOPS35FL7XIOZKKGQWSP3IYFE6B66KD4YOGJMWVC5PR",
//     graphAddress: "CCGCRYUTDRP52NOPS35FL7XIOZKKGQWSP3IYFE6B66KD4YOGJMWVC5PR",
//     symbol: "USDC",
//     logoURI: "https://raw.githubusercontent.com/trustw",
//     decimals: 7,
//     coinGeckoId: "usd-coin",
//   },
// ];

export const stellarTokens: Token[] = [
  {
    name: "USDC",
    address: "CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA",
    symbol: "USDC",
    logoURI:
      "https://assets.coingecko.com/coins/images/100/standard/Stellar_symbol_black_RGB.png",
    decimals: 7,
    coinGeckoId: "usd-coin",
  },
  {
    name: "BlabberCoin",
    address: "CBCU5VMZ3GNHHKJUWZ2GI7K36MEAXOJW2RJCIJHFPVFGBME3WADLXA6W",
    symbol: "BLAH",
    logoURI: "https://app.soroswap.finance/unknown-token.png",
    coinGeckoId: "",
    decimals: 7,
  },
  {
    name: "Yawnerium",
    address: "CCBJNX4B23ZDXEE3KRS2IAQJSLNQY4ZJ24K44BI7FYYIF5ZAZMRYPRRD",
    symbol: "YAWN",
    logoURI: "https://app.soroswap.finance/unknown-token.png",
    coinGeckoId: "",
    decimals: 7,
  },
  {
    name: "ZapatoToken",
    address: "CB77RFKDW446Q4ENKFOTJIXSYGOGP3GKSAD2RE3WVPYBJFUEG66TUFSJ",
    symbol: "ZAP",
    logoURI: "https://app.soroswap.finance/unknown-token.png",
    coinGeckoId: "",
    decimals: 7,
  },
  {
    name: "BoopToken",
    address: "CD5E7YM4MTL5S4B4FKLAMFLMXCN26L4QGPAS7JCVBG4TPW5EIP5WXIQO",
    symbol: "BEEP",
    logoURI: "https://app.soroswap.finance/unknown-token.png",
    coinGeckoId: "",
    decimals: 7,
  },
  {
    name: "SnoozerCoin",
    address: "CD6IN4UFNPDX35H7YB53XAA2XE6S2UPXL7AZL6DSFZFNNZSLE7FFSIVP",
    symbol: "SNOOZE",
    logoURI: "https://app.soroswap.finance/unknown-token.png",
    coinGeckoId: "",
    decimals: 7,
  },
  {
    name: "GigglyCoin",
    address: "CD4NTX2UXD2X257XCNSWRB45N5GUXVSHFY7L5W53IULIM5EVYAFENQGO",
    symbol: "GIGGLE",
    logoURI: "https://app.soroswap.finance/unknown-token.png",
    coinGeckoId: "",
    decimals: 7,
  },
  {
    name: "HahaToken",
    address: "CDME3GWAU7YSHVB6GWKDOQORR6TYKKQG6G7FDMMO7OPMQALBCNI5A2JR",
    symbol: "HAHA",
    logoURI: "https://app.soroswap.finance/unknown-token.png",
    coinGeckoId: "",
    decimals: 7,
  },
  {
    name: "LaughOutLoudToken",
    address: "CAZXNKR3XVKSPZLKRIZLXFFQ2BOHNAQHAWXEPHESKTMDGKY6ZJXALFGU",
    symbol: "LOL",
    logoURI: "https://app.soroswap.finance/unknown-token.png",
    coinGeckoId: "",
    decimals: 7,
  },
  {
    name: "veonov",
    address: "CA3T3BDJBIMCTM4GXRVXCL27QMXMWU44TTAWUOJND57CGRLJVA75LMLN",
    symbol: "VEON",
    logoURI: "",
    coinGeckoId: "",
    decimals: 7,
  },
  {
    name: "cyouxi",
    address: "CDJTAULP7GCE4AOOAAQ4P455QXON3KWCAKNWPDAF4PVIWSKDRS2TKTHI",
    symbol: "CYOU",
    logoURI: "",
    coinGeckoId: "",
    decimals: 7,
  },
  {
    name: "lazpia",
    address: "CB4IXKCOCT4Z4HL7BOHSDHL5Z5JJMOH4EJXDGK2QLXZU3Z5ZOOWBXOTD",
    symbol: "LAZP",
    logoURI: "",
    coinGeckoId: "",
    decimals: 7,
  },
  {
    name: "cyonov",
    address: "CBC2ZVRVACTQIIZZ6WA2ZN7JHBFWVTZURFZMBGNF6YITNZ2JQNDSGTNC",
    symbol: "CYON",
    logoURI: "",
    coinGeckoId: "",
    decimals: 7,
  },
];
